---
title: 'Paper from code'
author: "Stylianos Serghiou"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
params:
  PROPORTION_OF_DATA: 0.5
output:
  prettydoc::html_pretty:
    theme: hpstr      # or: architect; https://github.com/yixuan/prettydoc
    highlight: github # or: vignette
    toc: TRUE         # no toc_float available
    df_print: kable   # obviates %>% kable; does not replace styling though
---

<style>
p {

text-align: justify;
text-justify: interword;
padding: 0 0 0.5em 0

}
</style>

```{r knitr, echo=FALSE}
# Load packages
library(knitr)
library(rmdformats)
library(kableExtra)
library(ggplot2)


######### knitr

# Define chunk options
opts_chunk$set(
  echo = TRUE,
  cache = FALSE, # if TRUE, no need to rerun chunks
  # cache.lazy = TRUE,  # use with big objects (>1 GB)
  cache.comments = FALSE, # do not rebuild if comments change
  tidy = FALSE, # can play with this
  warning = FALSE,
  message = FALSE,
  comment = NA,
  fig.align = "center",
  fig.width = 7,
  fig.path = "Figs/", # export all figures to dir Figs
  linewidth = 91,
  width = 75
)

# Initialize hook
hook_output <- knit_hooks$get("output")

# Hook to wrap output text when it exceeds 'n' using linewidth
knit_hooks$set(output = function(x, options) {
  if (!is.null(n = options$linewidth)) {
    x <- knitr:::split_lines(x)

    # wrap lines wider than 'n'
    if (any(nchar(x) > n)) {
      x <- strwrap(x, width = n)
    }
    x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})

# Times a chunk and prints the time it took to run it under the chunk
# To time a chunk, include in the chunk options: {r my_chunk, timeit=TRUE}
knitr::knit_hooks$set(timeit = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now)
      now <<- NULL
      # use options$label if you want the chunk label as well
      paste("Time for this code chunk:", as.character(res))
    }
  }
}))


######### kableExtra

options(
  knitr.kable.NA = "", # replace NAs in tables with blank
  digits = 3 # round digits (doesn't work without this here!)
)

# Function to simplify table styling
sable <- function(tab, escape = TRUE, full_width = FALSE, drop = FALSE,
                  font_size = 12) {
  if (drop) {
    tab |>
      kable(escape = escape, booktabs = TRUE) |>
      kableExtra::collapse_rows(valign = "top") |>
      kableExtra::kable_styling(
        "striped",
        position = "center",
        full_width = full_width,
        font_size = font_size
      )
  } else {
    tab |>
      kable(escape = escape, booktabs = TRUE) |>
      kableExtra::kable_styling(
        "striped",
        position = "center",
        full_width = full_width,
        font_size = font_size
      )
  }
}


#########  ggplot2

# Set up preferred theme in ggplot2
my_theme <-
  # this and theme_minimal() are my favorite
  theme_light() +
  theme(
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.title.x = element_text(margin = margin(t = 15)),
    axis.title.y = element_text(margin = margin(r = 7)),
    legend.key = element_rect(colour = NA, fill = NA), # Avoid borders
    panel.border = element_blank(),
    text = element_text(color = "grey20"),
    title = element_text(face = "bold")
  )

# Make the above theme the default theme
original_theme <- theme_set(my_theme)
```

# Setup

## Imports

```{r}
library(dplyr)
library(ggplot2)
library(magrittr)
library(readr)
library(tidyr)
library(readxl)
library(styler)
```

## Parameters

```{r}
# Source locations
src_dir <- paste0(
  "~/Documents/Stanford/Huang_lab_rotation/Chow_derived_media/",
  "240308_chow_media_comparisons/"
)

src_dimensions <- "48hrs_snapshots/48hrs_cell_dimensions.xlsx"

# Destination locations
dst_dir <- paste0(
  "~/Documents/Stanford/Huang_lab_rotation/Chow_derived_media/",
  "240308_chow_media_comparisons/R_outputs/",
  "48hrs_cell_dimensions"
)
```

------------------------------------------------------------------------

# Read

```{r}
# Convert .xlsx files to readable .csv
write.csv(read_excel(paste0(src_dir, src_dimensions)),
  "48hrs_cell_dimensions.csv",
  row.names = FALSE
)

# Read all csv files and view output
cell_dimensions_ <- read_csv("48hrs_cell_dimensions.csv")

cell_dimensions_
```

------------------------------------------------------------------------

# Conform

Create file.

```{r}
cell_dimensions <- cell_dimensions_
```

------------------------------------------------------------------------

# Compute - Describe

Determine percentage difference in cell width compared to standard 1 um width.

```{r}
# Calculate SEs and percentages of BHIS standard and save as new columns.
cell_dimensions_mod <- cell_dimensions %>%
  mutate(
    width_SE = width_SD / sqrt(num_cells),
    length_SE = length_SD / sqrt(num_cells),
    width_percent_BHIS = (cell_width - first(cell_width)) /
      first(cell_width) * 100,
    length_percent_BHIS = (cell_length - first(cell_length)) /
      first(cell_length) * 100
  )

# Creates long form table to generate cluster plot
cell_dimensions_long <- cell_dimensions_mod %>%
  pivot_longer(
    cols = c(width_percent_BHIS, length_percent_BHIS),
    names_to = "parameter",
    values_to = "percent_difference_of_BHIS"
  )

cell_dimensions_long$comb_SD <- cell_dimensions_long$width_SD
cell_dimensions_long$comb_SD[seq(2, nrow(cell_dimensions_long), by = 2)] <-
  cell_dimensions_long$length_SD[seq(2, nrow(cell_dimensions_long), by = 2)]

cell_dimensions_long
```

------------------------------------------------------------------------

# Compute - Visualize

## Barplots

```{r}
# Plot
cell_dimensions_plot <- cell_dimensions_long %>%
  ggplot(aes(x = media, y = percent_difference_of_BHIS, fill = parameter)) +
  geom_col(position = "dodge") +
  labs(y = "percent of 1 um", title = "48hrs cell dimensions") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

# Save plot
ggsave(
  file.path(dst_dir, "48hrs_cell_dimensions.png"),
  cell_dimensions_plot,
  height = 4,
  width = 6
)

# Print
cell_dimensions_plot
```

------------------------------------------------------------------------

# Compute - Visualize

## Images

I am choosing an image on the following criteria: 1. Reflection of cell size 2. Reflection of media condition.

On the basis of this criteria, I will be illustrating the following image:

```{r}
# Choose image
from_experiment <- paste0(
  "~/Documents/Stanford/Huang_lab_rotation/",
  "Chow_derived_media/240308_chow_media_comparisons/"
)
from_condition <- "48hrs_snapshots/"
from_bhis <- "48hrs_ecoli_BHIS_1.tif"
from_15chowsd7pb <- "48hrs_ecoli_15chowDS7(PB)_1.tif"

# Copy paste to output directory
from <- file.path(from_experiment, from_condition, from_bhis)
from2 <- file.path(from_experiment, from_condition, from_15chowsd7pb)
to <- file.path(dst_dir, "48hrs_BHIS.tif")
to2 <- file.path(dst_dir, "48hrs_15chowSD7(PB).tif")
file.copy(from, to)
file.copy(from2, to2)
```

------------------------------------------------------------------------

# Compute - Analyze

This is where you can compute any p-values.

------------------------------------------------------------------------

# Write

```{r}
```

------------------------------------------------------------------------

# Reproducibility

## Linting and styling

```{r}
# Style current file
styler::style_file(
  path = rstudioapi::getSourceEditorContext()$path,
  style = tidyverse_style
)

# Lint current file
lintr::lint(rstudioapi::getSourceEditorContext()$path)
```

## Dependencies

```{r}
# Clean up project of libraries not in use
renv::clean()

# Update lock file with new packages
renv::snapshot()
```

## Containerization

```{r}
UPDATE_DOCKERFILE <- FALSE

# Only run this if option is set to TRUE
if (UPDATE_DOCKERFILE) {
  # Create a dockerfile from the session info
  my_dockerfile <- containerit::dockerfile(from = sessionInfo(), env = ls())
  # Write file
  write(my_dockerfile, file = "~/Dockerfile")
  print(my_dockerfile)
}
```

------------------------------------------------------------------------

# Documentation

## Session info

```{r}
print(sessionInfo(), locale = FALSE)
```

## References

```{r}
(.packages()) %>%
  sort() %>%
  lapply(citation) %>%
  lapply(c) %>%
  unique()
```
